[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "gigdownloader"
version = "1.0.1b1"
description = "GigDownloader - YouTube, Facebook, Instagram, X, TikTok, Threads and Pinterest downloader"
requires-python = ">=3.10"
dependencies = ["yt-dlp", "yt-dlp-threads"]

[project.scripts]
gigdownloader = "gigdownloader.cli:main"
gig = "gigdownloader.cli:main"

[tool.setuptools]
packages = ["gigdownloader"]
